name: kids_edu_teacher
description: Kids Edu Teacher Application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.6
  easy_localization: ^3.0.3
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  lottie: ^2.3.2
  youtube_player_flutter: ^8.1.2
  smooth_page_indicator: ^1.1.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  masked_text: ^1.1.2
  pinput: ^3.0.1
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  awesome_dialog: ^3.1.0
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
